tasks:
  - init: |
      mkdir build
      cmake -DCMAKE_INSTALL_PREFIX=/workspace/cmakels/install \
      -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug \
      -H/workspace/llvm-project/llvm -B/workspace/llvm-project/build "-GUnix Makefiles" \
      -DLLVM_TARGETS_TO_BUILD=X86 -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra"
      ln -s /workspace/cmakels/build/compile_commands.json .
      # TODO ninja
    prebuild: |
      mkdir -p build/.clangd
      clangd-indexer-10-rc1 --executor=all-TUs compile_commands.json > /workspace/cmakels/build/.clangd/clangd.dex

image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - ms-vscode.cmake-tools@1.3.0-beta2:D4zHFORWBgqtZI9hwWYNvA==
    - ms-vscode.cpptools@0.26.2:Pq/tmf2WN3SanVzB4xZc1g==
